name: myBoard CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17.0.6
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#Build
    - name: Build with Gradle
      run: ./gradlew clean build

# 전송할 파일을 담을 디렉토리 생성
    - name: Make Directory for deliver
      run: mkdir deploy
      
# Jar 파일 Copy
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy/   
      
# 압축파일 형태로 전달
    - name: Make zip file
      run: zip -r -qq -j ./springboot-intro-build.zip ./deploy      
      

# Deploy

    - name: Deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 --acl private ./myboard-post.zip s3://myboard-post/

